"""Pydantic request/response models for the GIFT Navigator API."""
from __future__ import annotations

from typing import Annotated, Literal, Optional

from pydantic import AfterValidator, BaseModel, Field

from .rules_engine import list_entity_ids


def _known_entity(v: str) -> str:
    if v not in list_entity_ids():
        raise ValueError(f"unknown entity '{v}'")
    return v


EntityId = Annotated[str, AfterValidator(_known_entity)]
# Anonymous per-tab id generated by the frontend; lets the funnel count sessions.
SessionId = Optional[Annotated[str, Field(max_length=64)]]


# ---- /recommend ----
class RecommendRequest(BaseModel):
    entity_id: str = Field(..., description="Entity chosen in the wizard, e.g. 'aif'")
    investor_type: Optional[Literal["retail", "nonretail"]] = Field(
        None, description="For AIF only: 'retail' or 'nonretail'"
    )
    session_id: SessionId = None


class EligibilityRule(BaseModel):
    rule: str
    source: str
    ref_url: Optional[str] = None
    value: Optional[str] = None  # human-readable resolved value, if any


class RecommendResponse(BaseModel):
    id: str
    name: str
    sub: str
    tag: str
    regulator: str
    what: str
    eligibility: list[EligibilityRule]
    timeline_label: str
    activities: list[str]
    last_reviewed: Optional[str] = None  # when the underlying figures were last checked


# ---- /tax/estimate ----
class TaxRequest(BaseModel):
    annual_income_usd: float = Field(..., ge=0)
    onshore_rate_pct: float = Field(..., ge=0, le=100)
    block_period_years: Optional[int] = None  # bounds live in tax_rules.json; tax_engine enforces
    advanced: bool = False
    surcharge_pct: Optional[float] = Field(None, ge=0, le=100)
    cess_pct: Optional[float] = Field(None, ge=0, le=100)
    mat_rate_pct: Optional[float] = Field(None, ge=0, le=100)
    apply_mat: bool = False

class TaxSeriesPoint(BaseModel):
    year: int
    phase: str
    onshore_cumulative: float
    ifsc_cumulative: float
    saving_cumulative: float

class TaxResponse(BaseModel):
    annual_income_usd: float
    onshore_rate_pct: float
    onshore_tax_annual: float
    ifsc_tax_annual: float
    annual_saving: float
    holiday_years: int
    holiday_total_saving: float
    block_period_years: int
    post_holiday_rate_pct: float
    block_total_saving: float
    disclaimer: str
    ifsc_post_holiday_annual: float
    advanced: bool
    surcharge_pct: float
    cess_pct: float
    mat_rate_pct: float
    apply_mat: bool
    series: list[TaxSeriesPoint]


# ---- /classify (free-text intake) ----
class ClassifyRequest(BaseModel):
    text: str = Field(..., min_length=2, max_length=2000)
    session_id: SessionId = None


class ClassifyResponse(BaseModel):
    entity_id: Optional[str]  # None when nothing matched - send the user to the wizard
    confidence: float
    method: str  # "keyword" or "llm" or "fallback"
    matched_terms: list[str] = []
    note: Optional[str] = None


# ---- /feedback ----
class FeedbackRequest(BaseModel):
    entity_id: EntityId
    helpful: bool
    comment: Optional[str] = Field(None, max_length=2000)
    session_id: SessionId = None


class FeedbackResponse(BaseModel):
    ok: bool
    feedback_id: int

# ---- /event (client-side funnel logging) ----
class EventRequest(BaseModel):
    kind: Literal["start", "tax_view"]
    entity_id: Optional[EntityId] = None
    session_id: SessionId = None


class EventResponse(BaseModel):
    ok: bool
